name: multipart_request
description: A flutter plugin to send a multipart request and get stream of progress.
version: 0.0.1
author: awazgyawali@gmail.com
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


flutter:
  plugin:
    androidPackage: com.brainants.multipartrequest
    pluginClass: MultipartRequestPlugin
